name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]


jobs: 

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Install Node Modules
      run: npm ci

    - name: PreDeploy
      run: npm run predeploy
      env: 
        CI: false

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build      

